# Generated by Django 2.2.4 on 2019-09-28 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('celular', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Sede')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('distrito', models.CharField(max_length=100, verbose_name='Distrito')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Director', verbose_name='Director')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cant_alumnos', models.IntegerField(verbose_name='Cantidad de alumnos')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salones',
            },
        ),
    ]
