# Generated by Django 2.2.4 on 2019-09-28 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='director',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Director', verbose_name='Director'),
        ),
    ]
