# Generated by Django 2.2.4 on 2019-09-28 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190927_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='cant_alumnos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Cantidad de alumnos'),
        ),
    ]
